version: '3.2'
services:
  animals:
    image: bersling/animals
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.frontend.rule=Host:animals2.tsmean.com"
        - "traefik.port=57253"
        - "traefik.docker.network=traefik"
    ports:
      - "57253:57253"
    networks:
      - traefik

networks:
  traefik:
    external: true
