version: '3.2'
services:
  animals:
    image: bersling/animals
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - web
      - default
    labels:
      - "traefik.frontend.rule=Host:animals2.tsmean.com"
      - "traefik.domain=tsmean.com"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
